backend:
  name: git-gateway
  branch: master
media_folder: "src/assets/images"
public_folder: "/assets/images"
site_url: "https://williamblackie.com"

local_backend: true
publish_mode: editorial_workflow
collections:
  - label: "Post" 
    name: "blog"
    folder: "src/posts/"
    create: true 
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
