backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "/images"
public_folder: "/assets/images"
site_url: "https://williamblackie.com"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "pages"
    files: 
      - label: "Home Page"
        name: "Home"
        file: "index.md"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "description", name: "description", widget: "string" }
